# inherit_from: .rubocop_todo.yml

SignalException:
  EnforcedStyle: only_raise

# Indent private and protected methods
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120
  IgnoreCopDirectives: true
  # Exclude:
  #   - "spec/**/*"

Layout/DotPosition:
  EnforcedStyle: trailing