language: ruby
rvm:
  - '1.8.7'
  - '1.9.3'
  - '2.0.0'
  - '2.1.0'
gemfile:
  - Gemfile
services:
  - redis-server
before_install:
  # 1.3.5 due to https://github.com/bundler/bundler/issues/2784
  - gem install bundler -v 1.3.5
script: bundle exec rspec spec
