language: ruby
rvm:
  - '1.8.7'
  - '1.9.3'
  - '2.0'
  - '2.1'
gemfile:
  - Gemfile
services:
  - redis-server
before_install:
  # # https://github.com/bundler/bundler/issues/2784
  # - gem update --system 2.1.11
  - gem --version
script: bundle exec rspec spec
