language: ruby
rvm:
- 1.8.7
- 1.9.3
- '2.0'
- '2.1'
gemfile:
- Gemfile
services:
- redis-server
before_install:
- gem --version
- wget http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
- sudo dpkg -i influxdb_latest_amd64.deb
- sudo /etc/init.d/influxdb start
- sleep 10
- 'curl -X POST ''http://localhost:8086/db?u=root&p=root'' -d ''{"name": "sandstorm_test"}'''
- 'curl -X POST ''http://localhost:8086/db/sandstorm_test/users?u=root&p=root'' -d
  ''{"name": "sandstorm", "password": "sandstorm"}'''
- 'curl -X POST ''http://localhost:8086/db/sandstorm_test/users/sandstorm?u=root&p=root''
  -d ''{"admin": true}'''
script: bundle exec rspec spec
notifications:
  hipchat:
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
    rooms:
      secure: GrQkFR0osJal/ciXSMydKYoQFzNwSxJCtWcaZtUgxEjba+xYbNEmT/RiRpq0MhGTAn5DUEcqHKENC0qVOxiBp8WPkCzcDLjmDzTpci1QDelB0faORfG8/71JpkrOoSvWzqg0QU3H4OgQaROE9mq3MdjYml6bH3M1ZtWSArX257Y=
