language: ruby
rvm:
- '2.0'
- '2.1'
- '2.2'
script: "bundle exec rspec"
services:
- redis-server
before_install:
- gem --version
- wget http://s3.amazonaws.com/influxdb/influxdb_0.8.8_amd64.deb
- sudo dpkg -i influxdb_0.8.8_amd64.deb
- sudo /etc/init.d/influxdb start
- sleep 8
- 'curl -X POST ''http://localhost:8086/db?u=root&p=root'' -d ''{"name": "zermelo_test"}'''
- 'curl -X POST ''http://localhost:8086/db/zermelo_test/users?u=root&p=root'' -d ''{"name": "zermelo", "password": "zermelo"}'''
- 'curl -X POST ''http://localhost:8086/db/zermelo_test/users/zermelo?u=root&p=root'' -d ''{"admin": true}'''
notifications:
  hipchat:
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
    rooms:
      secure: GrQkFR0osJal/ciXSMydKYoQFzNwSxJCtWcaZtUgxEjba+xYbNEmT/RiRpq0MhGTAn5DUEcqHKENC0qVOxiBp8WPkCzcDLjmDzTpci1QDelB0faORfG8/71JpkrOoSvWzqg0QU3H4OgQaROE9mq3MdjYml6bH3M1ZtWSArX257Y=
